title: "Andana.me"
email: narrative.wranger@gmail.com
description: >
  Data science narratives, methods, and tales from the front-lines. >
  >
  [About](https://andana.me)
  
url: "https://andana.me"
theme: jekyll-theme-minimal
twitter_username: tom_roderick
github_username: tomrod


