title: "Andana.me"
email: narrative.wranger@gmail.com
description: >
  Andana.me: data science narratives, methods, and tales from the front-lines.
  
url: "https://andana.me"
theme: jekyll-theme-minimal
twitter_username: tom_roderick
github_username: tomrod


