title: "Andana.me"
email: narrative.wranger@gmail.com
description: >
  Data science narratives, methods, and tales from the front-lines. 
  
url: "https://andana.me"
theme: jekyll-theme-minima 
twitter_username: tom_roderick
github_username: tomrod


